services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      # Optional: set N8N_BASIC_AUTH_ACTIVE=true etc.
      TZ: Europe/Sofia
    volumes:
      # Bind your host folder (inside Colima VM) to n8n's .n8n directory
      - /my-n8n-files:/home/node/.n8n:rw
      - /team_2_files:/home/node/files:rw

  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai
    ports:
      - "11235:11235"
    restart: unless-stopped
    shm_size: 1g