[project]
name = "clipclap-factory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "networkx>=3.5",
    "notebook>=7.4.3",
    "pandas>=2.3.0",
]
